/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.WindowConstants;
import ventanas.TextPrompt;
import modelos.*;
/**
 *
 * @author Jadri
 */
public class frmInicio extends javax.swing.JFrame {

    
    private TextPrompt tex;
    
    frmRegistro reg = new frmRegistro();
    /**
     * Creates new form frmInicio
     */
    public frmInicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        barraInicia.setVisible(false);
        tex = new TextPrompt("CORREO", txtCorreo);
        tex = new TextPrompt("CONTRASEÑA", txtPass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPan = new javax.swing.JPanel();
        inicioPan = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        lbUser = new javax.swing.JLabel();
        lbPass = new javax.swing.JLabel();
        btIniciar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbBien = new javax.swing.JLabel();
        lbDona = new javax.swing.JLabel();
        lbCora = new javax.swing.JLabel();
        lbVida = new javax.swing.JLabel();
        barraInicia = new javax.swing.JProgressBar();
        btIniciar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbSoft = new javax.swing.JLabel();
        lbDino = new javax.swing.JLabel();
        fondoImagen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio Sesion");

        fondoPan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setBorder(null);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        txtPass.setBorder(null);

        lbUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadri\\Documents\\NetBeansProjects\\DonaVida\\src\\main\\java\\imagenes\\user.png")); // NOI18N
        lbUser.setText("jLabel2");

        lbPass.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadri\\Documents\\NetBeansProjects\\DNvida\\src\\main\\java\\imagenes\\candado.png")); // NOI18N

        btIniciar.setBackground(new java.awt.Color(153, 153, 255));
        btIniciar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btIniciar.setText("Iniciar");
        btIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciarActionPerformed(evt);
            }
        });

        btSalir.setBackground(new java.awt.Color(153, 153, 255));
        btSalir.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 51, 255));

        jPanel2.setBackground(new java.awt.Color(102, 51, 255));

        lbBien.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        lbBien.setText("Inicio de Sesion");

        lbDona.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lbDona.setText("Dona");

        lbCora.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadri\\Documents\\NetBeansProjects\\DNvida\\src\\main\\java\\imagenes\\corazon.png")); // NOI18N

        lbVida.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
        lbVida.setText("Vida");

        btIniciar1.setBackground(new java.awt.Color(153, 153, 255));
        btIniciar1.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btIniciar1.setText("Registrarse");
        btIniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIniciar1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Recuperar Contraseña");

        javax.swing.GroupLayout inicioPanLayout = new javax.swing.GroupLayout(inicioPan);
        inicioPan.setLayout(inicioPanLayout);
        inicioPanLayout.setHorizontalGroup(
            inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioPanLayout.createSequentialGroup()
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(inicioPanLayout.createSequentialGroup()
                        .addContainerGap(105, Short.MAX_VALUE)
                        .addComponent(lbDona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbVida, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addComponent(lbBien))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioPanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioPanLayout.createSequentialGroup()
                        .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(inicioPanLayout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btIniciar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addGroup(inicioPanLayout.createSequentialGroup()
                                .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass)
                            .addComponent(barraInicia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inicioPanLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(74, 74, 74))))
        );
        inicioPanLayout.setVerticalGroup(
            inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicioPanLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lbBien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCora)
                    .addComponent(lbDona)
                    .addComponent(lbVida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(inicioPanLayout.createSequentialGroup()
                        .addComponent(barraInicia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPass, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addGroup(inicioPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btIniciar)
                    .addComponent(btSalir)
                    .addComponent(btIniciar1))
                .addGap(11, 11, 11))
        );

        fondoPan.add(inicioPan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 370, 400));

        lbSoft.setBackground(new java.awt.Color(0, 153, 153));
        lbSoft.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lbSoft.setText("Software:");
        fondoPan.add(lbSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 80, 20));

        lbDino.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadri\\Documents\\NetBeansProjects\\DNvida\\src\\main\\java\\imagenes\\dino.png")); // NOI18N
        fondoPan.add(lbDino, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 50, -1));

        fondoImagen.setIcon(new javax.swing.ImageIcon("C:\\Users\\Jadri\\Documents\\NetBeansProjects\\DonaVida\\src\\main\\java\\imagenes\\inicioS.jpg")); // NOI18N
        fondoPan.add(fondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondoPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciarActionPerformed
        // TODO add your handling code here:
        validar();
    }//GEN-LAST:event_btIniciarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btIniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIniciar1ActionPerformed
        reg.setVisible(true);
    }//GEN-LAST:event_btIniciar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraInicia;
    private javax.swing.JButton btIniciar;
    private javax.swing.JButton btIniciar1;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JPanel fondoPan;
    private javax.swing.JPanel inicioPan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBien;
    private javax.swing.JLabel lbCora;
    private javax.swing.JLabel lbDino;
    private javax.swing.JLabel lbDona;
    private javax.swing.JLabel lbPass;
    private javax.swing.JLabel lbSoft;
    private javax.swing.JLabel lbUser;
    private javax.swing.JLabel lbVida;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JPasswordField txtPass;
    // End of variables declaration//GEN-END:variables

    usuariosMET usua = new usuariosMET();
    usuariosModelo usuamod = new usuariosModelo();
    int contador;
    int segundos = 30;
    private Timer tiempo;
    
    public class BarraProgreso implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            String contraseña = String.valueOf(txtPass.getPassword());
            contador++;
            barraInicia.setValue(contador);
            if( contador == 100){
                tiempo.stop();
                if(barraInicia.getValue() == 100){
                    frmAdministrador admin = new frmAdministrador(usuamod);
                    frmNavegante vist = new frmNavegante(usuamod);
                    if(contraseña.equals("Administra")){
                    admin.setVisible(true);
                    }else{
                    vist.setVisible(true);}
                    dispose();
                }
            }
        }
    }
    
    
    private void validar() {
        String correo = txtCorreo.getText();
        String contraseña = String.valueOf(txtPass.getPassword());
        if(!"".equals(correo) || !"".equals(contraseña)){
            usuamod = usua.validar(correo, contraseña);
            if (usuamod.getCorreo()!=null && usuamod.getClave()!=null) {
            barraInicia.setVisible(true);
            contador=-1;
            barraInicia.setValue(0);
            barraInicia.setStringPainted(true);
            tiempo = new Timer(segundos, new BarraProgreso());
            tiempo.start();
            } else{
        JOptionPane.showMessageDialog(null, "Correo o la contraseña son incorrectos");
        }
    }
}
}
